---
version: 1
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-vvv"
  EE_BASE_IMAGE: 'automationhub.bcnconsulting.com/ee-minimal-rhel8:latest'
ansible_config: 'ansible.cfg'
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - RUN microdnf reinstall -y tzdata
...
